wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.46.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1732685360.150901
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 103
      3:
      - 13
      - 23
      4: 3.12.7
      5: 0.16.1
      6: 4.46.3
      8:
      - 1
      - 5
      13: darwin-arm64
